import os
import torch

def check_environment():
    """Verifies that the AI environment is using the Mac GPU."""
    print("\n--- 1. Checking Environment ---")
    
    # Check PyTorch version
    print(f"PyTorch Version: {torch.__version__}")
    
    # Check for Apple Silicon (MPS)
    if torch.backends.mps.is_available():
        print("SUCCESS: Apple Metal (MPS) Acceleration is AVAILABLE. ✅")
        print("Training will run on your Mac GPU.")
    else:
        print("WARNING: MPS not detected. Training will run on CPU (Slow). ⚠️")

def create_structure():
    """Creates the YOLO standard directory tree."""
    print("\n--- 2. Creating Folder Structure ---")
    
    # Define standard YOLO structure
    folders = [
        "dataset/images/train",
        "dataset/images/val",
        "dataset/labels/train",
        "dataset/labels/val",
        "models_export" # Place to save your final .pt files
    ]
    
    for folder in folders:
        if not os.path.exists(folder):
            os.makedirs(folder)
            print(f"Created: {folder}")
        else:
            print(f"Exists:  {folder}")

def create_yaml():
    """Generates the data.yaml file with your specific classes."""
    print("\n--- 3. Generating data.yaml ---")
    
    yaml_content = """# YOLOv8/v10 Dataset Configuration
# Generated by init_project.py

path: ./dataset  # dataset root dir
train: images/train  # train images (relative to 'path') 
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: head
  1: chest
  2: body
"""
    
    with open("data.yaml", "w") as f:
        f.write(yaml_content)
    
    print("Created: data.yaml with classes [Head, Chest, Body] ✅")

if __name__ == "__main__":
    check_environment()
    create_structure()
    create_yaml()
    print("\n--- Setup Complete ---")
    print("Next Steps:")
    print("1. Put 80% of your images in: dataset/images/train")
    print("2. Put 20% of your images in: dataset/images/val")
    print("3. Use CVAT to label them, and save .txt labels in corresponding /labels/ folders.")